### ISSUE TITLE
Add linkedIn URL's

### ISSUE THREAD

**Issue by beccablazak** [codeforamerica/fellows-map#13]
Just tried adding LinkedIn URL's to the popup boxes and the URL didn't show in the box

**Comment by beccablazak** [comment]
@svmatthews would be cool to get these in the pop up boxes today or tomorrow if possible

**Comment by beccablazak** [comment]
Also, could we potentially link to the CfAP people database for up to date info on all fellows?

**Comment by svmatthews** [comment]
Can do! Mind showing an example link for the CfAP?
