### ISSUE TITLE
Switch from leaflet.js to mapbox.js

### ISSUE THREAD

**Issue by lyzidiamond** [codeforamerica/fellows-map#19]
Like #2, but more breakdancing.
### Why should you switch to mapbox.js?
1. If you are adding a basemap styled in Mapbox Studio that will be uploaded to mapbox.com, it'll be super easy to add to your map with `L.mapbox.map()`. You can also store your data in mapbox.com and not have to worry about hosting other files, if you want.
2. We host our CDNs over HTTPS :smile: https://www.mapbox.com/mapbox.js/api/v2.1.8/
3. Blatant homerism

/cc @beccablazak @svmatthews @hamhands

**Comment by mapsam** [comment]
:dancer:
