### ISSUE TITLE
style basemap appropriately for CfA

### ISSUE THREAD

**Issue by svmatthews** [codeforamerica/fellows-map#2]
Could use mapbox to find a good red, white, and blue color scheme.

**Comment by svmatthews** [comment]
@hamhands has expressed interest in helping out here!

**Comment by beccablazak** [comment]
@svmatthews @hamhands awesome! I was playing around with Mapbox studio a little bit this afternoon...super fun

**Comment by svmatthews** [comment]
agreed! I had @hamhands show me the ropes on Friday last week. He's making a sweet Metal Map with @yuletide

**Comment by beccablazak** [comment]
@hamhands @svmatthews I don't know what a metal map is, but sounds cool

**Comment by svmatthews** [comment]
It's like a map, but [more metal](https://www.youtube.com/watch?v=xuotAxVTo2c) :metal:

**Comment by hamhands** [comment]
https://api.tiles.mapbox.com/v4/hamhands.32eaadfc/page.html?access_token=pk.eyJ1IjoiaGFtaGFuZHMiLCJhIjoiMksybk92QSJ9.TOMmDM4uWCY65kSLpS_Nww#4/46.86/-121.29

**Comment by beccablazak** [comment]
@hamhands whoa...that's a pretty intense looking map

**Comment by hamhands** [comment]
Yeah I know. If you go to Finland it looks like the whole landscape has been spattered with blood :metal:

**Comment by yuletide** [comment]
I'll just leave this here. From the good old days: http://mapoftheweek.blogspot.com/2009/02/map-of-week-heavy-metal-cartogram.html

**Comment by svmatthews** [comment]
> DJ Yuletide

**Comment by hamhands** [comment]
Awwwww I miss map of the week @yuletide

**Comment by hamhands** [comment]
And by that I mean I miss going to that blog that still exists.

**Comment by mapsam** [comment]
@beccablazak what about just using the Stamen Toner light tileset for now? http://maps.stamen.com/toner-lite/#12/37.7706/-122.3782

**Comment by migurski** [comment]
There’s a high-res version of those available for Retina screens as well. Not well-documented, but:

![regular resolution tile](http://tile.stamen.com/toner-lite/12/656/1582.png)

![double resolution tile](http://tile.stamen.com/toner-lite/12/656/1582@2x.png)

**Comment by mapsam** [comment]
Nice! @migurski what's the chance of being able to use the brigade tileset from http://www.codeforamerica.org/brigade/?

**Comment by hamhands** [comment]
Had I known about that tileset, this issue would not exist

**Comment by migurski** [comment]
I suppose you could just use it as-is—I think @ondrae set it up.

**Comment by mapsam** [comment]
:clap: 

![screen shot 2015-05-06 at 2 00 47 pm](https://cloud.githubusercontent.com/assets/1943001/7503507/53fa8f9a-f3f8-11e4-953f-5a467e64aa18.png)

**Comment by ondrae** [comment]
Looks good

Andrew Hyder
Developer Advocate :: 2013 Fellow
@hackyourcity http://twitter.com/hackyourcity

_National Day of Civic Hacking is June 6. *_Register your event
http://hackforchange.org/*
