### ISSUE TITLE
Search for fellow by name

### ISSUE THREAD

**Issue by mapsam** [codeforamerica/fellows-map#23]
There should be a searchbar that allows you to search for a fellow by name and open up their location on the map with their info

**Comment by mapsam** [comment]
Search is working! Still some bugs, but related to #27

![fellows-map-search](https://cloud.githubusercontent.com/assets/1943001/7505137/745325e8-f404-11e4-9bcf-a59a6c8f48ea.gif)

**Comment by mapsam** [comment]
Thanks @tiffani for being in my search GIF!

**Comment by tiffani** [comment]
![Success](http://media.giphy.com/media/12CvxNY8J5utEs/giphy.gif)
