### ISSUE TITLE
Detroit seal is 404'd

### ISSUE THREAD

**Issue by creade** [codeforamerica/fellows-map#39]
Looks like y'all gotta link to 
[http://www.codeforamerica.org/media/images/governments/**detriot**_seal.png](http://www.codeforamerica.org/media/images/governments/detriot_seal.png)
instead of 
[http://www.codeforamerica.org/media/images/governments/**detroit**_seal.png](http://www.codeforamerica.org/media/images/governments/detroit_seal.png)

**Comment by mapsam** [comment]
Indeed it is!

<img width="204" alt="screen shot 2015-07-06 at 7 04 21 pm" src="https://cloud.githubusercontent.com/assets/1943001/8537296/dca2a9a6-2411-11e5-8d4f-a2ef3894d142.png">

**Comment by mapsam** [comment]
Was just misspelled in the spreadsheet - all updated and fixed.

<img width="227" alt="screen shot 2015-07-06 at 7 05 35 pm" src="https://cloud.githubusercontent.com/assets/1943001/8537306/17ed318e-2412-11e5-85e2-66ed832bae60.png">
