### ISSUE TITLE
build filters

### ISSUE THREAD

**Issue by mapsam** [codeforamerica/fellows-map#4]
- [ ] ~~skillset~~
- [x] year
- [x] search by name #23

**Comment by mapsam** [comment]
Year! :birthday: 

![fellows-map-filter](https://cloud.githubusercontent.com/assets/1943001/7506268/9343cab2-f412-11e4-9dc8-403a49ecf246.gif)

**Comment by beccablazak** [comment]
Badass

**Comment by mapsam** [comment]
Going to hold on the `skill set` filter for now
