### ISSUE TITLE
make icons include name of fellow

### ISSUE THREAD

**Issue by svmatthews** [codeforamerica/fellows-map#5]
unsure of how to do this currently, but will take a look!

**Comment by svmatthews** [comment]
Also we'll need to spiderfy linearly instead of around a circle. I've submitted a [pull request](https://github.com/Leaflet/Leaflet.markercluster/pull/469) to the MarkerCluster repo to see if we can get this pushed as a feature. If not we can at least have a custom installation of markercluster.js with the functions listed in https://github.com/Leaflet/Leaflet.markercluster/issues/467

**Comment by svmatthews** [comment]
@beccablazak what do you think about including a small image of the fellow as well? Here's an option:

![screen shot 2015-03-27 at 3 27 52 pm](https://cloud.githubusercontent.com/assets/1943001/6878126/da960c3c-d495-11e4-9406-093900a223eb.png)

**Comment by beccablazak** [comment]
@svmatthews I like that a lot!

**Comment by svmatthews** [comment]
Great! I'll include it in the updates.
